### ISSUE TITLE
No push notification working

### ISSUE THREAD

**Issue by erossini** [VladislavAntonyuk/WorldExplorer#116]
Hello,
I was looking at your code here https://github.com/VladislavAntonyuk/WorldExplorer/commit/8ce130a77e1ad29c70c237074b23f5971324eae4#diff-033e38b5872051a85ed80103bb7a5b65c953fd7de051ef370a98e125bdb3d697

I configured Azure with a `Notification hub` and set the Google part. The code for `Android` runs without issues but the device is not registered in the Azure portal. 

![image](https://github.com/VladislavAntonyuk/WorldExplorer/assets/9497415/aac08478-204f-48e0-8384-ae3a7fa5b439)

I tried with different devices (emulators or real).

**Comment by VladislavAntonyuk** [comment]
Hi, do you call the code, that registers the device?

**Comment by erossini** [comment]
Yes, in the _MainActivitity_

    protected override async void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        CrossFingerprint.SetCurrentActivityResolver(() => this);
        CrossMauiMTAdmob.Current.Init(this, Constants.AndroidApp, Constants.MauiMTAdmobLicence);

        await DeviceInstallationService.RegisterDevice("languageinuse", Constants.PushNotificationSecret);
    }

With debug, I followed the code. I can see the call to `PutAsJsonAsync(...)`.

**Comment by erossini** [comment]
Sorry, I noticed just now that the request received an `Unauthorized error`.

<img width="495" alt="image" src="https://github.com/VladislavAntonyuk/WorldExplorer/assets/9497415/c4393644-8da8-4517-8bd2-a31ae13d577f">

**Comment by erossini** [comment]
Sorry to disturb you again. I can't find why I get the `Unauthorized error`. 

In Azure, I created a Notification hub (like in the first screenshot I posted) and the `DefaultListenSharedAccessSignature` is

```
Endpoint=sb://languageinuse.servicebus.windows.net/;SharedAccessKeyName=DefaultListenSharedAccessSignature;SharedAccessKey=11/Ecr0JEXXXGMYqCPZP4r0q89xdjlxxxxx=
```

So, in the `MainActivity`, I register the device like

```
await DeviceInstallationService.RegisterDevice("languageinuse", Constants.PushNotificationSecret);
```

where _languageinuse_ is the name of the hub (as in the endpoint) and the secret is the last part of the string. What do I do wrong? 

Thank you in advance for your help,
Enrico

**Comment by VladislavAntonyuk** [comment]
It's hard to say without knowing how you setup the azure. I suggest you try again with the steps described here https://vladislavantonyuk.github.io/articles/.NET-MAUI-Push-Notifications-using-Azure-Notification-Hub.-Part-1.-Setup-Azure-Notification-Hub and here

**Comment by erossini** [comment]
👋
I can't find the way to register the device and I tried quite hard. I still can't register my Windows app. So, I was working on the Android app. Using your original code, I get as a result of the call `Unauthorized`.

I created an Azure Notification Hub and the connection string is

> Endpoint=sb://languageinuse.servicebus.windows.net/;SharedAccessKeyName=DefaultListenSharedAccessSignature;SharedAccessKey=XfPbpiz2EGlsjsjAqEmFUoZJqNV+UM8qt9sl8K+15fU=

In the Google Firebase, I created the `Server Key` and added it to the configuration in the Notification Hub.

![image](https://github.com/VladislavAntonyuk/WorldExplorer/assets/9497415/681ca7a1-5f75-45a8-83cd-fb4f8c02c053)

With this configuration, I call the API and I get `Unauthorized`.

![image](https://github.com/VladislavAntonyuk/WorldExplorer/assets/9497415/0dfb6759-2caf-4dcb-afec-d0c724cf6e8e)

**Comment by VladislavAntonyuk** [comment]
I will probably record a video with steps, that you can reproduce to solve the issue

**Comment by erossini** [comment]
Thank you so much!

**Comment by erossini** [comment]
Always me 😁
Now, I can register the app on the Azure Notification Hub. The trick was that the app must be in your `Applications from personal account` tab and not in the `Owned applications` tab.

![image](https://github.com/VladislavAntonyuk/WorldExplorer/assets/9497415/3a87dd29-5d73-41ba-b1d6-92b9b6000c2a)


The `key` I have to use in the code, is the `Security key` I use for registering the app or the key from the `Access Policy` for the `Azure Notification Hub`  `DefaultListenSharedAccessSignature`? In any case, I tried both and it is now working; I always get `Unathorized`.

**Comment by erossini** [comment]
I found the issue. In your code, you are using always the `notificationHub` variable. From the documentation, the URL is different

> https://{notificationHubNamespace}.servicebus.windows.net/{notificationHub}/installations

where `notificationHubNamespace` is the main URL and `notificationHub` is the name of the hub.
By any change, do you know how to implement the iOS version?

Thank you in advance,
Enrico

**Comment by VladislavAntonyuk** [comment]
I don’t have Apple developer account to try and provide the example(
Official documentation describes the steps to get a certificate which you need to upload to Azure portal. After that the steps in the app should be the same

**Comment by erossini** [comment]
I have the certificate. What I don't know the configuration for the `deviceInstallation`. For example, in Android you have this

    var firebaseToken = await FirebaseMessaging.Instance.GetToken();
    var deviceInstallation = new
    {
        InstallationId = GetDeviceId(),
        Platform = "gcm",
        PushChannel = firebaseToken.ToString()
    };

Apart from the platform that I guess is `apns`, what is the `PushChannel`? I resd somewhere that I have to implement the call in this function in the `AppDelegate`

    [Export("application:didRegisterForRemoteNotificationsWithDeviceToken:")]
    public async void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
    {
        // ...
    }

**Comment by VladislavAntonyuk** [comment]
https://learn.microsoft.com/en-us/azure/notification-hubs/ios-sdk-get-started

**Comment by erossini** [comment]
I saw that document, but they explained how to configure the Azure Notification Hub. Also, this document is quite old, so, some of the steps are completely different. In the documentation, they use the Azure Notification Hub SDK and there is no indication of how to pass the `deviceInstallation` to the api.

**Comment by erossini** [comment]
I'm still fighting with the notification now in Apple. Do you have any idea how to fill the `deviceInstallation`? 

    var deviceInstallation = new
    {
        InstallationId = UIDevice.CurrentDevice.IdentifierForVendor.AsString(),
        Platform = "apns",
        PushChannel = ??
    };

I think I can use the `UIDevice` to get an id for the device but I have no clue how to get the PushChannel.

**Comment by VladislavAntonyuk** [comment]
this is a request to Notification Service API. I took it from here: https://learn.microsoft.com/en-us/previous-versions/azure/reference/mt621153(v=azure.100)

pushChannel - String - The PNS handle for this installation (in case of WNS the ChannelUri of the ApplicationTile).

**Comment by VladislavAntonyuk** [comment]
another suggestion: Setup it using Xamarin and Notification hub lib: https://learn.microsoft.com/en-us/azure/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started
and then see what request does your application send.

**Comment by erossini** [comment]
Finally, I found the solution and I [wrote a post](https://puresourcecode.com/dotnet/maui/maui-push-notifications-using-azure-notification-hub-for-ios/) to explain all the steps to send and receive push notification from Azure Notification Hub in iOS

**Comment by VladislavAntonyuk** [comment]
Thank you, I will link your post in my article
